services:
    phpbbmodders.banhammer.listener:
        class: phpbbmodders\banhammer\event\banhammer_listener
        arguments:
            - '@auth'
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@phpbbmodders.banhammer.core.bantime'
            - '%core.root_path%'
            - '%core.php_ext%'            
        tags:
            - { name: event.listener }
    phpbbmodders.banhammer.admin.controller:
        class: phpbbmodders\banhammer\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@phpbbmodders.banhammer.core.bantime'
    phpbbmodders.banhammer.core.bantime:
        class:  phpbbmodders\banhammer\core\bantime
        arguments:
            - '@user'
