services:
    rmcgirr83.printallposts.listener:
        class: rmcgirr83\printallposts\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
