name: Deploy via FTP to external hosting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  # rather than triggering on push, lets trigger on creating a release
  # this will let us deploy changes to github-pages staging, and then publish to prod
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-via-ftp:
    name: Deploy-via-FTP
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # SFTP the files up
      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.ftp_server }}
          remote-user: ${{ secrets.ftp_username }}
          private-ssh-key: ${{ secrets.ssh_private_key }}
          destination-path: ~/refugelarp.org/
#      # FTP the files up
#      - name: 📂 Sync files
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#        with:
#          server:   ${{ secrets.ftp_server }}
#          username: ${{ secrets.ftp_username }}
#          password: ${{ secrets.ftp_password }}
#          server-dir: refugelarp.org/
#          # set to dry-run to true to not actually publish but just get a list of what would be published
#          dry-run: false
#          exclude: |
#            **/.git*
#            **/.git*/**
#            **/node_modules/**
#            **/forum/**
#          # excluding the forum path, even though its not checked in to git, since the forum software exists
