name: Deploy via FTP to external hosting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-via-ftp:
    name: Deploy-via-FTP
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server:   ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          dry-run: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/forum/**
            # excluding the forum path, even though its not checked in to git, since the forum software exists

      
